### ISSUE TITLE
interrupts interfere with work

### ISSUE THREAD

**Issue by bamboo-master** [Seeed-Studio/Seeed_Arduino_AHT20#1]
esp8266.
I am using tm1637 display with AHT 20 and it works fine! But the project also has a 74hc595 display, it displays the clock, but because of the sensor it blinks continuously!
So far, I have solved the problem by taking readings 1 time per minute, using an ntp clock. "595" blinks once a minute (at least not endless).
I would like to find a way around this blinking!

**Comment by wangfreexx** [comment]
该程序使用了while+delay，你可以尝试使用定时器来驱动595
